builds:
  - id: docdev
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X main.Version={{.Version}}
    binary: docdev_{{ .Os }}_{{ .Arch }}
    main: main.go
    dir: go
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: phpdocdev
    name: docdev
archives:
- format: binary
  name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"