
name: publishmultipledockerimage

on:
  push:
    branches: ['master']
      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TAGS: [54, "54-alpine", 56, "56-alpine", 72, 74, 81]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - ${{format('php/{0}/**', matrix.TAGS)}}
              - php/conf/**
              - php/common/**
      - name: Run Buildx
        if: steps.filter.outputs.changed == 'true'
        continue-on-error: true
        run: |
          docker buildx build \
            -f php/${{ matrix.TAGS }}/Dockerfile \
            php/. \
            --platform linux/amd64,linux/arm64 \
            --push --tag ghcr.io/phpdocdev/php:${{ matrix.TAGS }}
  other:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TAGS: ["apache", "bind", "mailhog", "vpn"]
    outputs:
      matrix: ${{ steps.getfile.outputs.files }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - ${{format('{0}/**', matrix.TAGS)}}
      - name: Run Buildx
        if: steps.filter.outputs.changed == 'true'
        continue-on-error: true
        run: |
          docker buildx build \
            -f ${{ matrix.TAGS }}/Dockerfile \
            ${{ matrix.TAGS }}/. \
            --platform linux/amd64,linux/arm64 \
            --push --tag ghcr.io/phpdocdev/${{ matrix.TAGS }}
          
