
name: publishmultipledockerimage
# on:
#   push:
#     paths:
#       - 'php/**/Dockerfile'
on:
  push:
    branches: ['master']
      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      changed_other: ${{ steps.filter.outputs.other_files }}
      changed_php: ${{ steps.filter.outputs.php_files }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            php:
              - 'php/**'
            other:
              - '**'
            all:
              - '**'
  setup:
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TAGS: [54, 56, 72, 74, 81]
    steps:
      - name: checkout
        uses: actions/checkout@v3
#       - uses: dorny/paths-filter@v2
#         id: filter
#         with:
#           list-files: json
#           filters: |
#             php:
#               - 'php/**/Dockerfile'
#             changed:
#               - '**'
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      
      - uses: YassinEldeeb/has-changed-path@v2.1
        id: changed-paths
        with:
          paths: ${{format('php/{0}', matrix.TAGS)}}
      -
        name: Changed path
        run: |
          echo ${{ steps.changed-paths.outputs.changed }}
      -
        name: Available platforms
        run: exit 1
#       -
#         name: Available platforms
#         run: echo ${{contains(fromJSON(steps.filter.outputs.changed_files), '.github/workflows/docker-publish.yml')}}
#       -
#         name: Get path
#         if: steps.filter.outputs.php
#         run: |
#           echo php/${{ matrix.TAGS }}/Dockerfile
#       -
#         name: Get path2
#         if: steps.filter.outputs.php
#         run: |
#           echo ${{format('php/{0}/Dockerfile', matrix.TAGS)}}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Run Buildx
        if: contains(fromJSON(needs.changes.outputs.changed_php), format('php/{0}', matrix.TAGS))
        run: |
          docker buildx build \
            -f php/${{ matrix.TAGS }}/Dockerfile \
            php/. \
            --platform linux/amd64,linux/arm64 \
            --push --tag ghcr.io/phpdocdev/php:${{ matrix.TAGS }}
  other:
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      matrix:
        TAGS: ["apache", "bind", "mailhog"]
    outputs:
      matrix: ${{ steps.getfile.outputs.files }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Run Buildx
        if: contains(fromJSON(needs.changes.outputs.changed_other), format('{0}', matrix.TAGS))
        run: |
          docker buildx build \
            -f ${{ matrix.TAGS }}/Dockerfile \
            ${{ matrix.TAGS }}/. \
            --platform linux/amd64,linux/arm64 \
            --push --tag ghcr.io/phpdocdev/${{ matrix.TAGS }}
          
